apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gczf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gczf
    app.kubernetes.io/part-of: byoc-app-ngkw
  name: gczf
spec:
  rules:
  - host: gczf-byoc-rzez-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-qwp24.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: gczf
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
